# Generated by Django 5.0.1 on 2024-01-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_images'),
        ),
    ]
