# Generated by Django 5.0.1 on 2024-01-25 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseInfo', '0003_house_image1_house_image2_alter_house_image'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='userProfile.customuser'),
        ),
    ]
