# Generated by Django 5.0.1 on 2024-01-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseInfo', '0005_alter_house_created_by'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
